import AdminSidebar from '@/components/admin-sidebar'
import type { Metadata } from 'next'
import { Suspense } from 'react'
import Loading from './loading'

export const metadata: Metadata = {
  title: 'Templo Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Suspense fallback={<Loading />}>
      <AdminSidebar>{children}</AdminSidebar>
    </Suspense>
  )
}
