import type { Metadata } from 'next'
import { Suspense } from 'react'
import Loading from './loading'
import AdminSidebar from '@/components/admin-sidebar'

export const metadata: Metadata = {
  title: 'Templo Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Suspense fallback={<Loading />}>
      <div className='grid-cols-[250px_1fr] grid gap-10'>
        <AdminSidebar />
        <div>{children}</div>
      </div>
    </Suspense>
  )
}
